Iter15
eqkez0r/metric-collector pull request #15
Opened 2024-05-21 19:35 UTC by eqkez0r

2024-05-22 08:05 UTC, edylcrm requested changes

2024-05-22 08:05 UTC, edylcrm commented on internal/agent/generator/generator.go
> +	for k, v := range g.mp {
повторяется в нескольких местах, может вынести в отдельную функцию?

2024-05-22 08:05 UTC, edylcrm commented on internal/agent/poller/poller.go
> +	p.mu.Lock()
Здесь точно нужен mutex?

2024-05-22 08:05 UTC, edylcrm commented on internal/agent/poster/poster.go
> +	wg.Add(1)
Обычно такую конструкцию не пишут так как это тяжело читать и отслеживать. Функцию которую вызывают асинхронно должна оставаться синхронной и там где надо вызывать асинхронно. 
Лучше писать как то так:
```
for i := 0; i < p.settings.RateLimit; i++ {
		wg.Add(1)
		go func() {
		    defer wg.Done()
		    p.postRequest(<-requests, &wg)}
		}()
}
```

2024-05-22 20:27 UTC, eqkez0r commented on internal/agent/generator/generator.go
> +		select {
У меня тут возникла неприятная ситуация, после исправления начал ругаться statictest, что в целом логично, ибо я оставляю пустой default. Вот формулировка:
should not have an empty default case in a for+select loop; the loop will spin
Собственно на что ругается:
```
func (p *poster) errorLogger(done chan struct{}) {
	for {
		select {
		case <-done:
			return
		case err := <-p.errChan:
			p.logger.Error(err)
		default:
		}

	}
}
```

Как быть?

2024-05-24 09:05 UTC, edylcrm approved these changes

2024-05-24 09:40 UTC, merged